# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a90abb2009c854f4ead9504bc99f05660ea77d22769dfec7c10d8765017f543e4c62e284de8a96110139d66b69697ec5ce214a74d8563c283c8e641221cebd

test:
  secret_key_base: 7d442dfd2a9603a2a922bf415419c23e24703ab4823d0c49f77b5c7bb43924971e9e1ede1bec6c7faffbbd31962a76e611b217929e6af682ad0d6e57aa654b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
